version: '3.8'

services:
  trading-bot:
    build: .
    container_name: ai-trading-bot
    restart: unless-stopped
    environment:
      - APCA_API_KEY_ID=${APCA_API_KEY_ID}
      - APCA_API_SECRET_KEY=${APCA_API_SECRET_KEY}
      - APCA_API_BASE_URL=${APCA_API_BASE_URL:-https://paper-api.alpaca.markets}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - GSHEET_ID=${GSHEET_ID}
      - GSPREAD_JSON_PATH=/app/google-credentials.json
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./logs:/app/logs
      - ./performance:/app/performance
      - ./google-credentials.json:/app/google-credentials.json:ro
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
