services:
  - type: web
    name: ai-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GSPREAD_JSON_PATH
        sync: false
      - key: GSHEET_ID
        sync: false
    plan: starter
