services:
  # Web service for health checks (required for Render)
  - type: web
    name: ai-trading-bot-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: starter
    build:
      pythonVersion: 3.11.8
    envVars:
      - key: PORT
        value: 5000
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GSPREAD_JSON_PATH
        sync: false
      - key: GSHEET_ID
        sync: false
      - key: XAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FAL_KEY
        sync: false
      - key: DEEPINFRA_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: false

  # Background worker for intensive trading operations (optional)
  - type: worker
    name: ai-trading-bot-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
    plan: starter
    envVars:
      - key: ALPACA_API_KEY
        sync: false
      - key: ALPACA_SECRET_KEY
        sync: false
      - key: ALPACA_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GSPREAD_JSON_PATH
        sync: false
      - key: GSHEET_ID
        sync: false
    autoDeploy: false
