services:
  - type: worker
    name: ai-trading-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: ENV
        value: production
    autoDeploy: true
    plan: starter