services:
  - type: web
    name: ai-trading-ui
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
    plan: free
    envVars:
      - key: USER_SESSION_ID
        value: web-ui
      - key: REDIS_URL
        value: your_redis_url
      - key: ALPACA_PAPER_API_KEY
        value: your_key
      - key: ALPACA_PAPER_SECRET_KEY
        value: your_secret
      - key: ALPACA_PAPER_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: PAPER_TRADING_MODE
        value: true

  - type: worker
    name: ai-trading-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: USER_SESSION_ID
        value: background-worker
      - key: REDIS_URL
        value: your_redis_url
      - key: ALPACA_PAPER_API_KEY
        value: your_key
      - key: ALPACA_PAPER_SECRET_KEY
        value: your_secret
      - key: ALPACA_PAPER_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: PAPER_TRADING_MODE
        value: true
