services:
  - type: web
    name: ai-trading-bot-maximum-profitability
    env: python
    plan: starter
    pythonVersion: "3.11"
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: APCA_API_KEY_ID
        sync: false
      - key: APCA_API_SECRET_KEY
        sync: false
      - key: APCA_API_BASE_URL
        value: https://paper-api.alpaca.markets
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: GSHEET_ID
        sync: false
      - key: GSPREAD_JSON_PATH
        value: /opt/render/project/src/google-credentials.json
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONPATH
        value: /opt/render/project/src
    disk:
      name: ai-trading-bot-disk
      mountPath: /opt/render/project/src/models
      sizeGB: 1
